import Head from 'next/head';
import Image from 'next/image';
import Script from 'next/script';
import Link from 'next/link';
import KTIPW2 from '../../images/albums/2nd.png';
import Footer from '../../Components/Footer';
import Navbar from '../../Components/Navbar';

function BGC() {
  return (
    <div>
        <Head>
        <title>K This Is Pierre&apos;s World 2</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="max-w-[1440px] h-screen mx-auto px-5">
        
        <Navbar />

        <section className="my-8">
            <div className="max-w-7xl mx-auto">
                <div className="flex flex-col space-y-4 text-center items-center">
                    <div className="w-56">
                        <Image draggable="false" src={KTIPW2} width={0} height={0} alt="" />
                    </div>
                    <div>
                        <ul className="flex flex-col text-white">
                            <li>
                                <div className="flex flex-row justify-between">
                                    <div>?</div>
                                    <div>COMMING SOON!</div>
                                    <div></div>
                                </div>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </section>
    

        <section className="mt-20 pb-20">
            <div className="max-w-7xl mx-auto">
                <div className="text-center text-white text-2xl mb-5">
                  <h1>Stream K This Is Pierre&apos;s World</h1>
                </div>
                <div>
                  <ul className="flex flex-col md:flex-row md:space-x-8 text-white text-center items-center justify-center">
                      <li>
                        <a className="hover:opacity-60" target="blank" href="https://www.youtube.com/channel/UC7-iLTekrzSAj1q_YKI-6iw"><box-icon color="white" size="lg" type='logo' name='youtube'></box-icon></a>
                      </li>
                      <li>
                        <a className="hover:opacity-60" target="blank" href="https://music.apple.com/us/artist/k-pierre/513317653"><box-icon color="white" size="lg" name='apple' type='logo' ></box-icon></a>
                      </li>
                      <li>
                        <a className="hover:opacity-60" target="blank" href="https://open.spotify.com/artist/0BmpvDkzjv2SQuKPHTwevI?si=6hosNkrNRHeVhjlcojixPg&nd=1"><box-icon color="white" size="lg" name='spotify' type='logo' ></box-icon></a>
                      </li>
                      <li>
                        <a className="hover:opacity-60" target="blank" href="https://soundcloud.com/its-minime"><box-icon color="white" size="lg" name='soundcloud' type='logo' ></box-icon></a>
                      </li>
                  </ul>
                </div>
            </div>
        <Footer />
        </section>

      </main>
      
      <Script src="https://unpkg.com/boxicons@2.1.1/dist/boxicons.js"/>
    </div>
  )
}

export default BGC