import React from 'react';
import Image from 'next/image'
import Head from 'next/head';
import Link from 'next/link';
import Hello from '../images/hello.gif';
import Navbar from '../Components/Navbar';
import Footer from '../Components/Footer';

function contact() {

    const contactForm = (
        <div className="w-full mt-3">
            <form className="flex flex-col text-white space-y-3 items-center"
                name="contact-form"
                method="POST"
                action="sentmail">
                    <div className="flex flex-col w-1/2">
                        <label htmlFor="name">Name *</label>
                        <input className="p-1"
                        id="name"
                        name="name"
                        required
                        type="text"/>
                    </div>

                    <div className="flex flex-col w-1/2">
                        <label htmlFor="company">Company *</label>
                        <input className="p-1" id="company" name="company" required type="text" />
                    </div>

                    <div className="flex flex-col w-1/2">
                        <label htmlFor="email">E-mail Address *</label>
                        <input className="p-1" id="email" type="email" name="email" required />
                    </div>

                    <div className="flex flex-col w-1/2">
                        <label htmlFor="message">Message *</label>
                        <textarea className="h-28 text-black px-1" id="message" name="message" required></textarea>
                    </div>
                    
                    <div className="flex flex-col w-1/2 items-center">
                        <button className="bg-black border-2 border-white w-20 rounded-md hover:scale-125 hover:animate-pulse hover:bg-white hover:text-black" type="submit">Submit</button>
                    </div>
            </form>
        </div>
    );

  return (
    <div className="overflow-y-scroll">
      <Head>
        <title>K Pierre - Contact</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

       <main className="max-w-[1440px] h-screen mx-auto px-5">
            <Navbar />
            <div className="text-center">
                <Image draggable="false" src= {Hello} width={0} height={0} alt="" />   
            </div> 

            <div>
                {contactForm}
            </div>

            <Footer />   
       </main>

    </div>
  )
}

export default contact