import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import Footer from '../Components/Footer';
import KPW from '../images/albums/1st.jpg';
import KPWII from '../images/albums/2nd.png';
import BgCheck from '../images/albums/bgCheck.png';
import Script from 'next/script';
import Navbar from '../Components/Navbar';

export default function Music() {
  return (
    <div className="overflow-y-scroll">
      <Head>
        <title>K Pierre - Music</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="max-w-[1440px] h-screen mx-auto px-5">
        
        <Navbar />

        <section className="my-8">
          <div className="max-w-7xl mx-auto">
            <div className="text-center text-white text-2xl mb-5">
              <h1>Albums</h1>  
            </div>
            <div className="flex flex-col md:flex-row md:space-x-8 space-y-3 md:space-y-0 justify-center items-center">
              <Link href="/albums/KTIPW">
                <div className="kpw felx flex-col space-y-3 items-center text-center hover:opacity-60 cursor-pointer">
                    <div className="w-44">
                      <Image draggable="false" src={KPW} width={0} height={0} alt="" />
                    </div>
                    <div className="flex flex-col text-md text-white">
                      <h1>K This Is Pierre&apos;s World</h1>
                      <p>EP | 2021</p>
                    </div>
                </div>
              </Link>
              <Link href="/albums/BGC">
                <div className="bgc felx flex-col space-y-3 items-center text-center hover:opacity-60 cursor-pointer">
                    <div className="w-44">
                      <Image draggable="false" src={BgCheck} width={0} height={0} alt="" />
                    </div>
                    <div className="flex flex-col text-md text-white">
                      <h1>Background Check</h1>
                      <p>??? | ???</p>
                    </div>
                </div>
              </Link>
              <Link href="/albums/KTIPW2">
                <div className="kpw2 felx flex-col space-y-3 items-center text-center hover:opacity-60 cursor-pointer">
                    <div className="w-44">
                      <Image draggable="false" src={KPWII} width={0} height={0} alt="" />
                    </div>
                    <div className="flex flex-col text-md text-white">
                      <h1>K This Is Pierre&apos;s World 2</h1>
                      <p>??? | ???</p>
                    </div>
                </div>
              </Link>
            </div>
          </div>
        </section>

        <section className="mt-20 pb-20">
            <div className="max-w-7xl mx-auto">
                <div className="text-center text-white text-2xl mb-5">
                  <h1>Stream K Pierre</h1>
                </div>
                <div>
                  <ul className="flex flex-col md:flex-row md:space-x-8 text-white text-center items-center justify-center">
                      <li>
                        <a className="hover:opacity-60" target="blank" href="https://www.youtube.com/channel/UC7-iLTekrzSAj1q_YKI-6iw"><box-icon color="white" size="lg" type='logo' name='youtube'></box-icon></a>
                      </li>
                      <li>
                        <a className="hover:opacity-60" target="blank" href="https://music.apple.com/us/artist/k-pierre/513317653"><box-icon color="white" size="lg" name='apple' type='logo' ></box-icon></a>
                      </li>
                      <li>
                        <a className="hover:opacity-60" target="blank" href="https://open.spotify.com/artist/0BmpvDkzjv2SQuKPHTwevI?si=6hosNkrNRHeVhjlcojixPg&nd=1"><box-icon color="white" size="lg" name='spotify' type='logo' ></box-icon></a>
                      </li>
                      <li>
                        <a className="hover:opacity-60" target="blank" href="https://soundcloud.com/its-minime"><box-icon color="white" size="lg" name='soundcloud' type='logo' ></box-icon></a>
                      </li>
                  </ul>
                </div>
            </div>
        <Footer />
        </section>

      </main>
      
      <Script src="https://unpkg.com/boxicons@2.1.1/dist/boxicons.js"/>

    </div>
  )
}
