import { ArrowLeftIcon } from '@heroicons/react/solid';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import Footer from '../Components/Footer';
import Hoops from '../images/Hoops.gif';



export default function Home() {
  return (
    <div>
      <Head>
        <title>K Pierre&apos;s World</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="z-0">
      </div>
      <main>
        <div className="w-full h-full z-10 absolute top-0">
          <div className="max-w-[1440px] mx-auto">
            <div className="text-center">
              <div className="animated my-3">
                <Image draggable="false" width={0} height={0} src={Hoops} alt="" />
              </div>
              <div className="slogan">
                <h1 className="text-white text-3xl">&quot;K Pierre This Is Your World&quot;</h1>
              </div>
              <div className='my-3'></div>
              <div className="slogan">
                <h1 className="text-white text-3xl">Thank you! we will get back to you as soon as possible.</h1>
              </div>
              <div className="navigation mt-3">
                <ul className="flex flex-col space-y-3 text-white items-center text-2xl align-center">
                  <li className="hover:text-green-300">
                  <div >
                    <Link href="/">
                    <div className="text-white w-fit flex flex-col items-center hover:text-green-300 cursor-pointer">
                        <ArrowLeftIcon className="h-8 w-8" />
                        <div>
                        <span>Return Home</span>
                        </div>
                    </div>
                    </Link>
                </div>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </main>
      <div className="w-full absolute justify-center bottom-0 z-10">
        <Footer />
      </div>

    </div>
  )
}
