import React from 'react';
import Image from 'next/image'
import Head from 'next/head';
import Link from 'next/link';
import Sock from '../images/s.gif';
import Navbar from '../Components/Navbar';
import Footer from '../Components/Footer';

function shop() {
  return (
    <div className="overflow-y-scroll">
    <Head>
      <title>K Pierre - Contact</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

     <main className="max-w-[1440px] h-screen mx-auto px-5">
          <Navbar />
          <div className="text-center">
              <Image draggable="false" src={Sock} width={0} height={0} alt="" />
          <div>
              <h1 className="text-white text-4xl">Comming Soon</h1>
          </div>   
          </div> 

        <Footer />
     </main>

  </div>
  )
}

export default shop